[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "AMD ROCm HIP runtime for CubeCL"
edition.workspace = true
keywords = ["gpu", "amd", "rocm", "hip"]
license.workspace = true
name = "cubecl-hip"
readme.workspace = true
repository = "https://github.com/tracel-ai/cubecl/tree/main/crates/cubecl-hip"
version.workspace = true


[lints]
workspace = true


[features]
default = [
    "std",
    "cubecl-server/default",
    "cubecl-common/default",
    "cubecl-core/default",
]

persistence = ["cubecl-server/persistence"]
std = [
    "cubecl-server/std",
    "cubecl-common/std",
    "cubecl-core/std",
    "cubecl-cpp/std",
]

cpp = []

pliron-dump = ["cubecl-cpp/pliron-dump", "cubecl-llvm/pliron-dump"]
rocwmma = []

tracing = [
    "dep:tracing",
    "cubecl-server/tracing",
    "cubecl-common/tracing",
    "cubecl-core/tracing",
]

[dependencies]
# Runtime Deps
log = { workspace = true }
tracing = { workspace = true, features = ["attributes"], optional = true }

cubecl-common = { workspace = true, default-features = true, features = [
    "std",
    "hash",
] }
cubecl-environment = { workspace = true }
cubecl-core = { workspace = true, features = [
    "amd",
] }
cubecl-cpp = { workspace = true, features = [
] }
cubecl-hip-sys = { version = "7.14.6085001" }
cubecl-llvm = { workspace = true, features = [
    "std",
    "amdgpu",
] }
cubecl-monitoring = { workspace = true, features = [
    "amdgpu-busy-percent",
    "gpu-engine-counters",
] }
cubecl-server = { workspace = true }

bytemuck = { workspace = true }

derive-new = { workspace = true }
half = { workspace = true }
paste = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
cubecl-core = { workspace = true, default-features = true, features = [
    "export_tests",
] }
cubecl-std = { workspace = true, features = [
    "export_tests",
] }
test-log = { workspace = true, features = ["trace"] }
