[package]
authors = ["Genna Wingert"]
categories = ["algorithms"]
description = "Compiler optimizations for CubeCL"
edition.workspace = true
keywords = ["gpu", "compiler"]
license.workspace = true
name = "cubecl-opt"
readme.workspace = true
repository = "https://github.com/tracel-ai/cubecl/tree/main/crates/cubecl-opt"
version.workspace = true


[lints]
workspace = true


[features]
default = ["std", "cubecl-common/default", "cubecl-ir/default"]
std = ["cubecl-common/std"]

tracing = ["cubecl-common/tracing", "cubecl-ir/tracing", "cubecl-core/tracing"]


[dependencies]
cubecl-common = { path = "../cubecl-common", version = "=0.11.0-pre.3", default-features = false }
cubecl-core = { path = "../cubecl-core", version = "=0.11.0-pre.3", default-features = false }
cubecl-environment = { path = "../cubecl-environment", version = "=0.11.0-pre.3", default-features = false }
cubecl-ir = { path = "../cubecl-ir", version = "=0.11.0-pre.3", default-features = false }

pliron = { workspace = true }

derive-new = { workspace = true }
derive_more = { workspace = true }
downcast-rs = { workspace = true }
foldhash = { workspace = true }
hashbrown = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
smallvec = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
expect-test = { workspace = true }
test-log = { workspace = true, features = ["trace"] }
